#include<iostream.h>
#include<conio.h>
void main()
{
  clrscr();
  int a,b,c;
  cout<<"enter the value of a"<<endl;
  cin>>a;
  cout<<"enter the value of b"<<endl;
  cin>>b;
  c=a+b;
  cout<<"the addition is"<<endl;
  cout<<c;

  int e,f,g;
  cout<<"enter the value of e"<<endl;
  cin>>e;
  cout<<"enter the value of f"<<endl;
  cin>>f;
  g=e-f;
  cout<<"The subtreaction is"<<endl;
  cout<<g;

  int x,y,z;
  cout<<"enter the value of x"<<endl;
  cin>>x;
  cout<<"enter the value of y"<<endl;
  cin>>y;
  z=x*y;
  cout<<"The multiflication is"<<endl;
  cout<<z;

  float h,i,j;
  cout<<"enter the value of h"<<endl;
  cin>>h;
  cout<<"enter the value of i"<<endl;
  cin>>i;
  j=h/i;
  cout<<"the division is"<<endl;
  cout<<j;
  getch();

}